###

POST http://localhost:3000/medics/
Content-Type: application/json

{
    "id": 223,
    "name": "Andrea",
    "lastname": "perez",
    "identifier": "123"
    
}

###

PUT http://localhost:3000/medics/1
Content-Type: application/json

{
    "name": "Leonor"
}

###

GET http://localhost:3000/medics/

###

GET http://localhost:3000/medics/1

###

DELETE  http://localhost:3000/medics/2

###

GET http://localhost:3000/medics/page/0

###